//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractIconBorder {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractIconBorder.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 There Are {0} Images In Total！Output Path：{1} 的當地語系化字串。
        /// </summary>
        internal static string BatchConvertSuccessed {
            get {
                return ResourceManager.GetString("BatchConvertSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Black Tolerance Must Be Number 的當地語系化字串。
        /// </summary>
        internal static string BlackToleranceMustBeNumber {
            get {
                return ResourceManager.GetString("BlackToleranceMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can Not Load Image: {0} 的當地語系化字串。
        /// </summary>
        internal static string CanNotLoadImage {
            get {
                return ResourceManager.GetString("CanNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Choose Image First 的當地語系化字串。
        /// </summary>
        internal static string ChooseImageFirst {
            get {
                return ResourceManager.GetString("ChooseImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Ignore Border Must Be Number 的當地語系化字串。
        /// </summary>
        internal static string IgnoreBorderMustBeNumber {
            get {
                return ResourceManager.GetString("IgnoreBorderMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There&apos;s No Image Can Be Save 的當地語系化字串。
        /// </summary>
        internal static string NoImageForSave {
            get {
                return ResourceManager.GetString("NoImageForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PNG File|*.png 的當地語系化字串。
        /// </summary>
        internal static string OpenPNGFileFilter {
            get {
                return ResourceManager.GetString("OpenPNGFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Failed 的當地語系化字串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Image 的當地語系化字串。
        /// </summary>
        internal static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Image Failed:  的當地語系化字串。
        /// </summary>
        internal static string SaveImageFailed {
            get {
                return ResourceManager.GetString("SaveImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image Has Been Saved To:  的當地語系化字串。
        /// </summary>
        internal static string SaveImageSuccessWithPath {
            get {
                return ResourceManager.GetString("SaveImageSuccessWithPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PNG Files|*.png 的當地語系化字串。
        /// </summary>
        internal static string SavePNGFileFilter {
            get {
                return ResourceManager.GetString("SavePNGFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Success 的當地語系化字串。
        /// </summary>
        internal static string SaveSuccessed {
            get {
                return ResourceManager.GetString("SaveSuccessed", resourceCulture);
            }
        }
    }
}
